# Module manifest for module 'VBAF'
#
# Generated by: Henning
#
# Generated on: 1/25/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VBAF.psm1'

# Version number of this module.
ModuleVersion = '1.0.1'

# Supported PSEditions
CompatiblePSEditions = @('Desktop')

# ID used to uniquely identify this module
GUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

# Author of this module
Author = 'Henning'

# Company or vendor of this module
CompanyName = 'VBAF Project'

# Copyright statement for this module
Copyright = '(c) 2025 Henning. All rights reserved.'

# Description of the functionality provided by this module
Description = @'
Visual Business Automation Framework (VBAF) - A PowerShell-based AI/RL platform.

VBAF combines neural networks, reinforcement learning, and visual dashboards to create
adaptive automation solutions. Built entirely in PowerShell 5.1 from scratch.

Features:
- Neural networks with backpropagation (solve XOR and beyond)
- Q-Learning agents with experience replay
- Multi-agent reinforcement learning systems
- Real-time learning visualization dashboards
- Business simulation environments
- Generative art with aesthetic rewards
- Comprehensive examples and documentation

Perfect for:
- Learning AI/ML concepts hands-on
- Building adaptive automation workflows
- Multi-agent simulations
- Intelligent business process automation
- Generative/creative applications

Unique Position: PowerShell 5.1 + AI + RL + Visual + Business
'@

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
    'System.Windows.Forms',
    'System.Drawing'
)

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'New-VBAFNeuralNetwork',
    'New-VBAFAgent',
    'Start-VBAFCastleCompetition',
    'Get-VBAFVersion',
    'Get-VBAFExamples',
    'Test-VBAF'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'AI',
            'MachineLearning',
            'ReinforcementLearning',
            'NeuralNetwork',
            'QLearning',
            'MultiAgent',
            'Automation',
            'Visualization',
            'Business',
            'Simulation',
            'GenerativeArt',
            'Dashboard',
            'PowerShell',
            'Education',
            'FromScratch'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/JupyterPS/VBAF/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/JupyterPS/VBAF'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Version 1.0.0 (January 2025)

### Initial Release - Foundation Complete!

**Core Features:**
- Multi-layer neural networks with backpropagation
- Q-Learning agents with epsilon-greedy exploration
- Experience replay for stable learning
- Real-time visualization dashboards

**Components:**
- Core neural network primitives (Neuron, Layer, Activation)
- RL agents (Q-Learning, Experience Replay, Q-Table)
- Business simulation (CompanyAgent, MarketEnvironment)
- Generative art (Castle Competition, Aesthetic Rewards)
- Visualization (Learning Dashboard, Graph Renderer, Metrics Collector)

**Examples:**
- XOR problem solver (neural network demo)
- Castle Q-Learning agent (generative RL)
- Multi-agent market simulation (business)
- 3-agent castle competition (emergent coordination)
- Validation dashboard (foundation proof)

**Documentation:**
- Complete API reference
- Getting started guide
- Theory explanations
- Multiple working examples

**Tested On:**
- PowerShell 5.1 (Windows PowerShell)
- Windows 10/11

**What's Next:**
- Advanced RL algorithms (PPO, A3C, SAC)
- Computer vision extensions (CNN)
- NLP integration
- Additional case studies
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}